version: '3.9'
services:
    server:
      container_name: flask_app
      build: .
      command: gunicorn --workers=4 --bind 0.0.0.0:5000 main:app
      ports:
        - 5000:5000
      restart: unless-stopped

    minio:
      image: minio/minio
      command: server --console-address :9005 /data
      ports:
        - '9000:9000'
        - '9005:9005'
      environment:
        - MINIO_ROOT_USER=minio
        - MINIO_ROOT_PASSWORD=miniopassword
      restart: always
      volumes:
         - ./minio-data:/data
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
        interval: 30s
        timeout: 20s
        retries: 3
