"""first migthation

Revision ID: 208e61f4ef73
Revises: 
Create Date: 2024-04-14 13:43:50.985455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '208e61f4ef73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('login', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('sex', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('additional_information',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_login', sa.String(), nullable=False),
                    sa.Column('about_me', sa.Text(), nullable=False),
                    sa.Column('interests', sa.Text(), nullable=True),
                    sa.Column('z', sa.String(), nullable=True),
                    sa.Column('height', sa.Integer(), nullable=True),
                    sa.Column('education', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_login'], ['users.login'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_login')
                    )
    op.create_table('photos',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_login', sa.String(), nullable=False),
                    sa.Column('img', sa.Text(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['user_login'], ['users.login'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('profiles',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_login', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['user_login'], ['users.login'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('photos')
    op.drop_table('additional_information')
    op.drop_table('users')
    # ### end Alembic commands ###
